### ISSUE TITLE
实践中是否可以爬取他人的微博数据

### ISSUE THREAD

**Issue by ForeverQ** [lzjun567/crawler_html2pdf#7]
看到文档中提到爬取微博数据时需要 cookies，是否意味着非本人账户（无密码）的微博无法爬取？

**Comment by lzjun567** [comment]
一样的可以爬，不过要解析网页了，而不是直接用微博提供的接口了

**Comment by ForeverQ** [comment]
这两天研究了下，用浏览器的控制台也能找到 json 数据的 url 地址。
